In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [2]:
from os import chdir
chdir('/content/drive/My Drive/huyen/face_expression/RAF_DB/')

In [ ]:
!unzip "/content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/Image.zip" -d "/content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/"

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/Image/PrivateTest_51684471.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/Image/PrivateTest_57411661.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/Image/PrivateTest_59294605.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/Image/PrivateTest_63034657.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/Image/PrivateTest_63597529.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/Image/PrivateTest_64589477.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/Image/PrivateTest_65117768.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/Image/PrivateTest_66424699.jpg  
  infla

In [ ]:
!unzip "/content/drive/My Drive/huyen/face_expression/RAF-DB/boundingbox.zip" -d "/content/drive/My Drive/huyen/face_expression/RAF-DB/"

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
  inflating: /content/drive/My Drive/huyen/face_expression/RAF-DB/boundingbox/train_07272_boundingbox.txt  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF-DB/boundingbox/train_07273_boundingbox.txt  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF-DB/boundingbox/train_07274_boundingbox.txt  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF-DB/boundingbox/train_07275_boundingbox.txt  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF-DB/boundingbox/train_07276_boundingbox.txt  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF-DB/boundingbox/train_07277_boundingbox.txt  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF-DB/boundingbox/train_07278_boundingbox.txt  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF-DB/boundingbox/train_07279_boundingbox.txt  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF-DB/boundingbox/t

In [ ]:
!git clone https://github.com/JiaweiShiCV/Amend-Representation-Module.git

Cloning into 'Amend-Representation-Module'...
remote: Enumerating objects: 147, done.
remote: Counting objects: 100% (147/147), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 147 (delta 80), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (147/147), 305.45 KiB | 3.05 MiB/s, done.
Resolving deltas: 100% (80/80), done.


In [ ]:
!mv Amend-Representation-Module/* ./
!rm -r Amend-Representation-Module/

In [ ]:
!git clone https://github.com/NVIDIA/apex

Cloning into 'apex'...
remote: Enumerating objects: 8048, done.
remote: Counting objects: 100% (135/135), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 8048 (delta 66), reused 65 (delta 28), pack-reused 7913
Receiving objects: 100% (8048/8048), 14.11 MiB | 8.73 MiB/s, done.
Resolving deltas: 100% (5467/5467), done.
Checking out files: 100% (343/343), done.


In [3]:
%cd apex
!pip install -v --no-cache-dir ./

/content/drive/My Drive/huyen/face_expression/RAF_DB/apex
Created temporary directory: /tmp/pip-ephem-wheel-cache-vlw2kt9r
Created temporary directory: /tmp/pip-req-tracker-qx1yyn51
Created requirements tracker '/tmp/pip-req-tracker-qx1yyn51'
Created temporary directory: /tmp/pip-install-uyfqxbed
Processing /content/drive/My Drive/huyen/face_expression/RAF_DB/apex
  Created temporary directory: /tmp/pip-req-build-8ymgo692
  Added file:///content/drive/My%20Drive/huyen/face_expression/RAF_DB/apex to build tracker '/tmp/pip-req-tracker-qx1yyn51'
    Running setup.py (path:/tmp/pip-req-build-8ymgo692/setup.py) egg_info for package from file:///content/drive/My%20Drive/huyen/face_expression/RAF_DB/apex
    Running command python setup.py egg_info


    torch.__version__  = 1.8.1+cu101


    running egg_info
    creating /tmp/pip-req-build-8ymgo692/pip-egg-info/apex.egg-info
    writing /tmp/pip-req-build-8ymgo692/pip-egg-info/apex.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-

In [5]:
chdir('/content/drive/My Drive/huyen/face_expression/RAF_DB/')

In [6]:
!python train_raf-db.py 


Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
100% 44.7M/44.7M [00:00<00:00, 103MB/s] 
batch_size: 256
Train set size: 12271
Validation set size: 3068
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.001
    weight_decay: 0.0001
)
---Epoch: 1---
[Epoch 1] Training accuracy: 0.6561. Loss: 0.958 LR: 0.001000
[Epoch 1] Validation accuracy:0.6855. Loss:0.941
tensor([4., 0., 4.,  ..., 6., 6., 6.], device='cuda:0')
Model saved.
best_acc:0.6855
---Epoch: 2---
[Epoch 2] Training accuracy: 0.7966. Loss: 0.572 LR: 0.000900
[Epoch 2] Validation accuracy:0.7960. Loss:0.568
tensor([4., 0., 6.,  ..., 6., 6., 6.], device='cuda:0')
Model saved.
best_acc:0.796
---Epoch: 3---
[Epoch 3] Training accuracy: 0.8413. Loss: 0.450 LR: 0.000810
[Epoch 3] Validation accuracy:0.8083. Loss:0.533
tensor([4., 0., 4.,  ..., 2., 3., 6.], device='cuda:0')
Model saved.
best_acc:0.8083
---Epo

In [ ]:
!python test_raf-db.py 

Loading checkpoint weights... ./models/RAF-DB/best_model.pth
Validation set size: 3068
Validation accuracy:0.8527.


In [ ]:
!python test_raf-db.py 

Loading checkpoint weights... ./models/RAF-DB/best_model.pth
Validation set size: 7178
Validation accuracy:0.4408.


In [10]:
!python plot_confusion_matrix.py

<Figure size 640x480 with 1 Axes>
