In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [2]:
from os import chdir
chdir('/content/drive/My Drive/huyen/face_expression/RAF_DB/')

In [3]:
!unzip "/content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/TrainImage.zip" -d "/content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/"

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/TrainImage/Training_93581503.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/TrainImage/Training_94056429.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/TrainImage/Training_94113647.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/TrainImage/Training_94627563.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/TrainImage/Training_95587256.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/TrainImage/Training_96149283.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/TrainImage/Training_96197039.jpg  
  inflating: /content/drive/My Drive/huyen/face_expression/RAF_DB/datasets/FER_2013/TrainImage/Training_962074

In [ ]:
!mv ./datasets/FER_2013/TrainImage/* ./datasets/FER_2013/Image/

In [4]:
%cd apex
!pip install -v --no-cache-dir ./

/content/drive/My Drive/huyen/face_expression/RAF_DB/apex
Created temporary directory: /tmp/pip-ephem-wheel-cache-fb_lxw36
Created temporary directory: /tmp/pip-req-tracker-s7m_pecb
Created requirements tracker '/tmp/pip-req-tracker-s7m_pecb'
Created temporary directory: /tmp/pip-install-srpu7xwa
Processing /content/drive/My Drive/huyen/face_expression/RAF_DB/apex
  Created temporary directory: /tmp/pip-req-build-hjhqgquy
  Added file:///content/drive/My%20Drive/huyen/face_expression/RAF_DB/apex to build tracker '/tmp/pip-req-tracker-s7m_pecb'
    Running setup.py (path:/tmp/pip-req-build-hjhqgquy/setup.py) egg_info for package from file:///content/drive/My%20Drive/huyen/face_expression/RAF_DB/apex
    Running command python setup.py egg_info


    torch.__version__  = 1.8.1+cu101


    running egg_info
    creating /tmp/pip-req-build-hjhqgquy/pip-egg-info/apex.egg-info
    writing /tmp/pip-req-build-hjhqgquy/pip-egg-info/apex.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-

In [5]:
chdir('/content/drive/My Drive/huyen/face_expression/RAF_DB/')

In [ ]:
!python train_resnet_fer2013.py 


batch_size: 256
Train set size: 28709
Validation set size: 3589
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.001
    weight_decay: 0.0001
)
---Epoch: 1---
[Epoch 1] Training accuracy: 0.5357. Loss: 1.223 LR: 0.001000
[Epoch 1] Validation accuracy:0.5475. Loss:1.210
tensor([0., 5., 4.,  ..., 6., 0., 0.], device='cuda:0')
Model saved.
best_acc:0.5475
---Epoch: 2---
[Epoch 2] Training accuracy: 0.6240. Loss: 0.993 LR: 0.000900
[Epoch 2] Validation accuracy:0.5762. Loss:1.241
tensor([4., 6., 4.,  ..., 3., 3., 3.], device='cuda:0')
Model saved.
best_acc:0.5762
---Epoch: 3---
[Epoch 3] Training accuracy: 0.6646. Loss: 0.893 LR: 0.000810
[Epoch 3] Validation accuracy:0.6102. Loss:1.236
tensor([3., 3., 5.,  ..., 0., 5., 6.], device='cuda:0')
Model saved.
best_acc:0.6102
---Epoch: 4---
[Epoch 4] Training accuracy: 0.6977. Loss: 0.812 LR: 0.000729
[Epoch 4] Validation accuracy:0.6372. Loss:0.981
tensor([3., 4., 6.,  ..., 5., 1., 6.], device='cuda:0

In [ ]:
!python test_raf-db.py 

Loading checkpoint weights... ./models/RAF-DB/best_model.pth
Validation set size: 3068
Validation accuracy:0.8527.


In [ ]:
!python test_raf-db.py 

Loading checkpoint weights... ./models/RAF-DB/best_model.pth
Validation set size: 7178
Validation accuracy:0.4408.


In [ ]:
!python plot_confusion_matrix.py

<Figure size 640x480 with 1 Axes>
